/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // First: Intro
    {
      type: 'doc',
      id: 'intro', // refers to intro.md
    },
    // Second: Glossary
    {
      type: 'doc',
      id: 'glossary', // refers to glossary.md
    },
    // Then: the numbered folders, in order
    {
      type: 'category',
      label: 'Introduction to Tricot',
      items: [{ type: 'autogenerated', dirName: '01-introduction-to-tricot' }],
    },
    {
      type: 'category',
      label: 'Planning',
      items: [{ type: 'autogenerated', dirName: '02-planning' }],
    },
    {
      type: 'category',
      label: 'Experimental Design',
      items: [{ type: 'autogenerated', dirName: '03-experimental-design' }],
    },
    {
      type: 'category',
      label: 'Climmob Suite',
      items: [{ type: 'autogenerated', dirName: '04-climmob-suite' }],
    },
    {
      type: 'category',
      label: 'Implementation',
      items: [{ type: 'autogenerated', dirName: '05-implementation' }],
    },
    {
      type: 'category',
      label: 'Data Analysis',
      items: [{ type: 'autogenerated', dirName: '06-data-analysis' }],
    },
    {
      type: 'category',
      label: 'Feedback & Dissemination',
      items: [{ type: 'autogenerated', dirName: '07-feedback-dissemination' }],
    },
    {
      type: 'category',
      label: 'Good, Bad & Ugly',
      items: [{ type: 'autogenerated', dirName: '08-good-bad-ugly' }],
    },
    {
      type: 'category',
      label: 'FAQ and Resources',
      items: [{ type: 'autogenerated', dirName: '09-FAQ and resources' }],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [{ type: 'autogenerated', dirName: '10-appendices' }],
    },
  ],
   
};

export default sidebars;
