/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // First: Intro
    {
      type: 'doc',
      id: 'intro', // refers to intro.md
    },
    
    // Then: the numbered folders, in order
    {
      type: 'category',
      label: 'Introduction to tricot',
      items: [{ type: 'autogenerated', dirName: '01-intro' }],
    },
    {
      type: 'category',
      label: 'Preparation',
      items: [{ type: 'autogenerated', dirName: '02-preparation' }],
    },
    {
      type: 'category',
      label: 'Design',
      items: [{ type: 'autogenerated', dirName: '03-design' }],
    },
    {
      type: 'category',
      label: 'Recruitment',
      items: [{ type: 'autogenerated', dirName: '04-recruitment' }],
    },
    {
      type: 'category',
      label: 'Distribution',
      items: [{ type: 'autogenerated', dirName: '05-distribution' }],
    },
    {
      type: 'category',
      label: 'Execution',
      items: [{ type: 'autogenerated', dirName: '06-execution' }],
    },
    {
      type: 'category',
      label: 'Observation',
      items: [{ type: 'autogenerated', dirName: '07-observation' }],
    },
    {
      type: 'category',
      label: 'Compilation',
      items: [{ type: 'autogenerated', dirName: '08-compilation' }],
    },
    {
      type: 'category',
      label: 'Analysis',
      items: [{ type: 'autogenerated', dirName: '09-analysis' }],
    },
     {
      type: 'category',
      label: 'Feedback and dissemination',
      items: [{ type: 'autogenerated', dirName: '10-feedback' }],
    },
     {
      type: 'category',
      label: 'Evaluation',
      items: [{ type: 'autogenerated', dirName: '11-evaluation' }],
    },
     {
      type: 'category',
      label: 'FAQ and resources',
      items: [{ type: 'autogenerated', dirName: '12-faq-and-resources' }],
    },
       {
      type: 'category',
      label: 'Tricot case studies',
      items: [{ type: 'autogenerated', dirName: '13-case-studies' }],
    },
    {
      type: 'doc',
      id: 'glossary', // refers to glossary.md
    },
    
  ],
   
};

export default sidebars;
