---
sidebar_position: 1
---

# Glossary

From short guide

ClimMob
Online software for the design and management of any tricot experiment (www.climmob.net). The database of all tricot projects is stored here. Project implementers also use ClimMob for the analysis of results and the generation of information outputs at the end of the project.

Balancing a trial
‘Balancing’ the trial means that all technology options are spread across all the participating villages. Each village will receive packages with 
consecutive numbers (1, 2, 3, 4, 5, etc.) and not random numbers (3, 11, 9, 23, 1, etc.). If this principle is followed, each of these villages will receive a balanced set and all of the technology options will be tested and evaluated.

Evaluation criteria
The 5 to 10 criteria that will be evaluated within the tricot experiment. These criteria should be chosen in consultation with all stakeholders. 
For example: Plant height, disease resistance, yield, and others.

Explanatory variables
Information about meteorology and agronomic management of the trials, serves to improve the analysis. The explanatory variables refine the results and help to identify the most suitable variety for the local conditions of every farmer. Examples: Use of irrigation, use of fertilization, 
season was rainier or drier than usual, etc.

Field agents
Lead farmers of rural communities, field workers, or extension agents. They are trained and remunerated by the implementing organization to assist the farmers in the execution and evaluation of their trials. They collect the data from the farmers and pass them on to the project implementers.

Implementing organization/ project implementers
The organization that is in charge of carrying out and monitoring the project. It can be an NGO, a government service, or a research program, among other options. Implementers have the major responsibilities in the project, for example:
• Training the field agents and farmers
• Distributing the trial packages
• Carrying out the data analysis once all data is collected and compiled
• Feeding back the information to the farmers via the field agents.

Infosheet
Personalized information output for every farmer. It is generated automatically using ClimMob and includes:
• Names of the three technology options that the farmer received and tested
• Names of the most recommended option for their farm
• Information about where to obtain more material of the preferred technology option (if applicable).

Observation card
A pictorial form printed on thick paper, on which farmers mark their observations of the technology options being tested on their plots. A generic design can be found for downloading at climmob.net and can be adapted to the local requirements.

ODK Collect
A free app available for download from Google Play Store to all Android-based mobile devices. ODK Collect is used for farmer registration and 
data collection in tricot projects.

Farmers / participating farmers
Women and men who participate in a tricot experiment by managing their own tricot trial and carrying out the observations, marking the observations on the observation card at the appropriate dates, and eventually reporting the observations to the local field agents. Their recruitment should involve considerations of gender, age and other demographic factors, as well as their task related to the technology under evaluation. In some tricot trials, non-farmers participate, based on their role in food processing, trading, retailing or consumption.

Randomization
The balanced creation of sets of three varieties from the full pool of varieties. The randomization is generated by the ClimMob software and is required to prepare the trial packages.

Researchers
Experts studying or using the agricultural technology under evaluation. They select the technology options to be included in the project and supply experimental material for each technology option to the implementing organization.

Technology
With tricot, many different kinds of farm innovations can be tested. Crop varieties can be one kind of agricultural technology, but irrigation systems, fertilizers, fertilizer dosage, or cropping styles and tillage systems are also ‘technologies’ that can be tested using the tricot approach. Within each technology, there are different variants or options (see next entry ‘Technology options’).

Technology options
Each tricot experiment focuses on one agricultural technology (for example, ‘fertilizer composition’), but tests several technology options 
(fertilizer composition X, fertilizer composition Y, etc.). These technology options should in principle be suitable to local conditions and have the potential to be adopted by some of the farmers.  The researchers select the technology options, and they are recommended to begin a first experiment made up of between 8 to 12 options.

Trial package
A bag given to every farmer at the initial workshop. The large bag is marked with a number and a QR code. It contains: (i) three small bags containing material of the different technology options ( marked with ‘A’, ‘B’, and ‘C’); (ii) an observation card; and (iii) an explanatory brochure about the tricot process.

Tricot
The word ‘tricot’ is derived from three words: Triadic comparison of technology options. ‘Triadic’ refers to the sets of three technology options that are compared in each trial. In technical jargon, three things define tricot: (1) the use of incomplete blocks of three items (to make the threshold of participation low in terms of farm size and to make it cognitively manageable), (2) the use of ranking as the main way to report observations (to facilitate digital data collection and to make it possible to cultivate a tricot plot with very little training), and (3) the limited control of experimental conditions (following usual technology use practice to maximize external validity).

Trial plot
A small area within or at the margin of the farmer’s production plot, with representative soil conditions. It is divided into three equal parts, for the testing of the three technology options assigned to the farmer.

Tricot trial
Field test of different technological options, in sets of three, each grown and observed by a farmer in a small designated area of her/his 
own farm.